const AccessControl = require('accesscontrol');
const ac = new AccessControl();

exports.roles = (function () {
  ac.grant('user')
    .updateOwn('password')
    .readOwn('place')
    .updateOwn('place')
    .deleteOwn('place')
    .readOwn('profile')
    .updateOwn('profile')
    .deleteOwn('profile')
    .readOwn('product')
    .updateOwn('product')
    .deleteOwn('product')
    .readOwn('subuser')
    .updateOwn('subuser')
    .deleteOwn('subuser')
    .readAny('subuser_key')
    .readOwn('file')
    .updateOwn('file')
    .deleteOwn('file')
    .readOwn('booking')
    .updateOwn('booking')
    .readOwn('freetime')
    .updateOwn('freetime')
    .readOwn('notification')
    .readAny('product_key')
    .readAny('workshift')
    .readAny('support')
    .readAny('employee');

  ac.grant('manager').extend('user');

  ac.grant('admin')
    .extend('user')
    .updateAny('password')
    .readOwn('setting')
    .updateAny('setting')
    .deleteAny('setting')
    .readAny('place')
    .updateAny('place')
    .deleteAny('place')
    .readAny('profile')
    .updateAny('profile')
    .deleteAny('profile')
    .readAny('product')
    .updateAny('product')
    .deleteAny('product')
    .readAny('subuser')
    .updateAny('subuser')
    .deleteAny('subuser')
    .updateAny('subuser_key')
    .deleteAny('subuser_key')
    .readAny('file')
    .updateAny('file')
    .deleteAny('file')
    .readAny('booking')
    .updateAny('booking')
    .deleteAny('booking')
    .readAny('freetime')
    .updateAny('freetime')
    .deleteAny('freetime')
    .readAny('notification')
    .updateAny('notification')
    .deleteAny('notification')
    .updateAny('product_key')
    .deleteAny('product_key')
    .updateAny('workshift')
    .deleteAny('workshift')
    .updateAny('support')
    .deleteAny('support')
    .updateAny('employee')
    .deleteAny('employee');

  ac.grant('sdmin').extend('user').extend('admin').readAny('setting');

  return ac;
})();
